# Default values for go-web-app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sureshkcloud/go-web-app-k8s
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v4"

ingress:
  enabled: false
  className: ""
  anatations: {}
  #
  #
  hosts:
    - host: chart-example-local
      paths:
        - path: /
          pathType: ImplementationSpecific
